<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-9TCQ07PF" failures="1" tests="3" name="RegressionTest" time="20.669" errors="0" timestamp="2024-02-27T11:34:43 IST">
  <testcase classname="com.ap.testlayer.SignupTest" name="validate_signup_into_application_valid_details" time="1.401">
    <failure type="java.lang.AssertionError" message="expected [https://ap-automation.odoo.com/my] but found [https://ap-automation.odoo.com/web/signup]">
      <![CDATA[java.lang.AssertionError: expected [https://ap-automation.odoo.com/my] but found [https://ap-automation.odoo.com/web/signup]
at com.ap.testlayer.SignupTest.validate_signup_into_application_valid_details(SignupTest.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- validate_signup_into_application_valid_details -->
  <testcase classname="com.ap.testlayer.LoginTest" name="validate_login_functinality_with_valid_credentials" time="1.492"/>
  <testcase classname="com.ap.testlayer.AddressTest" name="addNewAddress" time="10.844"/>
</testsuite> <!-- RegressionTest -->
